// Intent citation: docs/architecture/ADR-005-provider-fabric-routing.md
// Intent citation: docs/architecture/ADR-006-addon-runtime-sdk.md

import type {
  AddOnInstallation,
  AddOnManifest,
  AgentDefinition,
  ArchiveAutomationPolicy,
  ArchivePolicy,
  CapabilityGrant,
  ChannelDefinition,
  ChatProject,
  ComputeFabricState,
  ConversationThread,
  CoreService,
  ModelStrategyState,
  ProviderExecutionAdapterPolicy,
  ProviderProfile,
  ProviderRoutingState,
  ProviderRuntimeNode,
  ResonantShellState,
  WorkspaceDefinition,
} from "./contracts";

const grant = (
  capability: CapabilityGrant["capability"],
  granted: boolean,
  scope: CapabilityGrant["scope"],
  revocationBehavior: CapabilityGrant["revocationBehavior"],
): CapabilityGrant => ({
  capability,
  granted,
  scope,
  revocationBehavior,
});

export const coreServices: CoreService[] = [
  {
    id: "shell.core",
    label: "ResonantOS Shell",
    status: "ready",
    owner: "core",
    description: "Desktop shell, windowing, event bus, settings, add-on registry, and permissions.",
  },
  {
    id: "strategist.core",
    label: "Strategist",
    status: "ready",
    owner: "core",
    description: "Primary trusted AI identity. Default name is Augmentor and it fronts the user relationship.",
  },
  {
    id: "setup.core",
    label: "Resonant Engineer Agent",
    status: "ready",
    owner: "core",
    description: "ResonantOS caretaker agent for onboarding, repair, provider setup, add-on installation, and recovery flows.",
  },
  {
    id: "living-archive.core",
    label: "Living Archive",
    status: "ready",
    owner: "core",
    description: "Core memory service with scoped reads, intake-only add-on writes, and Strategist-owned ingest.",
  },
];

export const providerProfiles: ProviderProfile[] = [
  {
    id: "shared-minimax",
    label: "Shared MiniMax",
    providerType: "minimax",
    authSource: "shared-vault",
    authMethod: "subscription",
    authTier: "experimental",
    apiBaseUrl: "https://api.minimax.io/v1",
    allowedModels: ["MiniMax-M3"],
    primaryModel: "MiniMax-M3",
    fallbackModel: undefined,
    modelContext: [
      {
        model: "MiniMax-M3",
        maxContextTokens: 1_000_000,
        tokenEstimateMethod: "provider-metadata",
        source: "provider-default",
      },
    ],
    consumerScopes: ["strategist", "setup", "archive-ingest", "telegram-channel"],
    shared: true,
    status: "ready",
    credentialStatus: "missing",
  },
  {
    id: "shared-openai",
    label: "Shared OpenAI",
    providerType: "openai",
    authSource: "shared-vault",
    authMethod: "subscription",
    authTier: "experimental",
    allowedModels: ["gpt-5.5", "gpt-5.4-mini"],
    primaryModel: "gpt-5.5",
    fallbackModel: "gpt-5.4-mini",
    modelContext: [
      {
        model: "gpt-5.5",
        maxContextTokens: 128_000,
        tokenEstimateMethod: "provider-metadata",
        reservedReasoningTokens: 6_400,
        source: "provider-default",
      },
      {
        model: "gpt-5.4-mini",
        maxContextTokens: 128_000,
        tokenEstimateMethod: "provider-metadata",
        reservedReasoningTokens: 6_400,
        source: "provider-default",
      },
    ],
    consumerScopes: ["strategist", "setup", "archive-ingest", "telegram-channel"],
    shared: true,
    status: "fallback",
    credentialStatus: "missing",
  },
  {
    id: "shared-zai-glm",
    label: "Shared Z.AI GLM",
    providerType: "openai-compatible",
    authSource: "shared-vault",
    authMethod: "api-key",
    authTier: "supported",
    apiBaseUrl: "http://127.0.0.1:18789/v1",
    allowedModels: ["zai/glm-5.2"],
    primaryModel: "zai/glm-5.2",
    fallbackModel: undefined,
    modelContext: [
      {
        model: "zai/glm-5.2",
        maxContextTokens: 195_000,
        tokenEstimateMethod: "provider-metadata",
        source: "provider-default",
      },
    ],
    consumerScopes: ["strategist", "setup", "archive-ingest", "telegram-channel"],
    shared: true,
    status: "fallback",
    credentialStatus: "missing",
  },
  {
    id: "shared-local",
    label: "Shared Local Runtime",
    providerType: "local",
    authSource: "manual",
    authMethod: "local-runtime",
    authTier: "supported",
    allowedModels: ["batiai/gemma4-e2b:q4"],
    primaryModel: "batiai/gemma4-e2b:q4",
    fallbackModel: undefined,
    modelContext: [
      {
        model: "batiai/gemma4-e2b:q4",
        maxContextTokens: 8_192,
        tokenEstimateMethod: "provider-metadata",
        source: "runtime-node",
      },
    ],
    consumerScopes: ["obsidian", "setup", "recovery"],
    shared: true,
    status: "fallback",
    credentialStatus: "configured",
  },
  {
    id: "gx10-local-llama",
    label: "GX10 llama.cpp Runtime",
    providerType: "openai-compatible",
    authSource: "manual",
    authMethod: "local-runtime",
    authTier: "supported",
    apiBaseUrl: "http://192.168.1.77:30004/v1",
    allowedModels: ["Qwen3.6-35B-A3B-Q4_K_M.gguf"],
    primaryModel: "Qwen3.6-35B-A3B-Q4_K_M.gguf",
    fallbackModel: undefined,
    modelContext: [
      {
        model: "Qwen3.6-35B-A3B-Q4_K_M.gguf",
        maxContextTokens: 400_000,
        tokenEstimateMethod: "provider-metadata",
        source: "runtime-node",
      },
    ],
    consumerScopes: ["strategist", "setup", "archive-ingest", "recovery"],
    shared: true,
    status: "ready",
    credentialStatus: "configured",
  },
];

export const runtimeNodes: ProviderRuntimeNode[] = [
  {
    id: "node-minimax-cloud",
    label: "MiniMax Cloud Runtime",
    providerProfileId: "shared-minimax",
    kind: "cloud",
    locality: "cloud",
    endpoint: "https://api.minimax.io/v1",
    supportedModels: ["MiniMax-M3"],
    authTier: "experimental",
    healthState: "ready",
    deployableOnDemand: false,
    notes: ["Subscription-capable route with experimental auth posture."],
  },
  {
    id: "node-openai-cloud",
    label: "OpenAI Cloud Runtime",
    providerProfileId: "shared-openai",
    kind: "cloud",
    locality: "cloud",
    supportedModels: ["gpt-5.5", "gpt-5.4-mini"],
    authTier: "experimental",
    healthState: "ready",
    deployableOnDemand: false,
    notes: ["Cloud route available when the provider profile is configured and healthy."],
  },
  {
    id: "node-zai-glm-cloud",
    label: "Z.AI GLM Gateway Runtime",
    providerProfileId: "shared-zai-glm",
    kind: "cloud",
    locality: "desktop-local",
    endpoint: "http://127.0.0.1:18789/v1",
    supportedModels: ["zai/glm-5.2"],
    authTier: "supported",
    healthState: "ready",
    deployableOnDemand: false,
    notes: ["OpenClaw/Z.AI GLM fallback route using the configured zai/glm-5.2 model id."],
  },
  {
    id: "node-local-resurrect",
    label: "Local Resurrect Runtime",
    providerProfileId: "shared-local",
    kind: "local",
    locality: "desktop-local",
    supportedModels: ["batiai/gemma4-e2b:q4"],
    authTier: "supported",
    healthState: "deployable",
    deployableOnDemand: true,
    notes: ["Prepared fallback runtime for emergency recovery, currently targeting a local Gemma 4 E2B build."],
  },
  {
    id: "node-gx10-qwen",
    label: "GX10 Qwen 35B llama.cpp Runtime",
    providerProfileId: "gx10-local-llama",
    kind: "remote-user-owned",
    locality: "lan-remote",
    endpoint: "http://192.168.1.77:30004/v1",
    supportedModels: ["Qwen3.6-35B-A3B-Q4_K_M.gguf"],
    authTier: "supported",
    healthState: "ready",
    deployableOnDemand: false,
    notes: [
      "Verified on 2026-05-16 through /health, /v1/models, and a chat completion probe. Served by llama.cpp on GX10 port 30004.",
    ],
  },
];

export const providerExecutionAdapters: ProviderExecutionAdapterPolicy[] = [
  {
    id: "cloud-minimax-compatible",
    label: "MiniMax Compatible Cloud Adapter",
    supportedProviderTypes: ["minimax"],
    supportedRuntimeKinds: ["cloud"],
    supportedAuthMethods: ["subscription", "api-key", "custom"],
    supportsReasoningEffort: false,
    supportsStreaming: true,
    supportsAbort: true,
    requiresCredential: true,
    experimental: true,
    notes: ["Uses the MiniMax-compatible cloud chat path through the host service."],
  },
  {
    id: "cloud-openai-compatible",
    label: "OpenAI Compatible HTTP Adapter",
    supportedProviderTypes: ["openai", "openai-compatible"],
    supportedRuntimeKinds: ["cloud", "local", "remote-user-owned"],
    supportedAuthMethods: ["api-key", "subscription", "oauth", "local-runtime", "custom"],
    supportsReasoningEffort: true,
    supportsStreaming: true,
    supportsAbort: true,
    requiresCredential: false,
    experimental: true,
    notes: ["Uses the OpenAI-compatible chat path for cloud providers and user-owned local HTTP runtimes."],
  },
  {
    id: "local-ollama",
    label: "Local Ollama Adapter",
    supportedProviderTypes: ["local"],
    supportedRuntimeKinds: ["local", "remote-user-owned"],
    supportedAuthMethods: ["local-runtime"],
    supportsReasoningEffort: false,
    supportsStreaming: true,
    supportsAbort: true,
    requiresCredential: false,
    experimental: false,
    notes: ["Uses the desktop-local Ollama runtime through the host service."],
  },
];

export const providerRouting: ProviderRoutingState = {
  policyEngineId: "routing.core",
  executionAdapters: providerExecutionAdapters,
  fallbackPolicies: [
    {
      id: "core-default",
      label: "Core Default Fallback",
      orderedProviderProfileIds: ["shared-minimax", "shared-zai-glm", "shared-openai", "gx10-local-llama", "shared-local"],
      orderedRuntimeNodeIds: ["node-minimax-cloud", "node-zai-glm-cloud", "node-openai-cloud", "node-gx10-qwen", "node-local-resurrect"],
      allowExperimentalAuth: true,
      allowResurrection: true,
      onFailure: "degrade",
    },
    {
      id: "strict-supported-only",
      label: "Strict Supported Routes",
      orderedProviderProfileIds: ["gx10-local-llama", "shared-local"],
      orderedRuntimeNodeIds: ["node-gx10-qwen", "node-local-resurrect"],
      allowExperimentalAuth: false,
      allowResurrection: true,
      onFailure: "hard-stop",
    },
  ],
  recoveryActions: [
    {
      id: "resurrect-core-local",
      label: "Resurrect Local Fallback",
      trigger: "panic-button",
      targetAgentIds: ["strategist.core", "setup.core"],
      runtimeNodeId: "node-local-resurrect",
      prepared: true,
      note: "Deploy the prepared local runtime and rewire Strategist and Setup to it.",
    },
  ],
  experimentalPolicy: {
    allowOptIn: true,
    note: "Experimental auth or runtime routes must be visibly marked and can be excluded by routing policy.",
  },
};

export const computeFabric: ComputeFabricState = {
  policyEngineId: "compute-fabric.core",
  nodes: [
    {
      id: "compute-desktop-local",
      label: "Desktop Local Host",
      kind: "desktop-local",
      trustTier: "local-owned",
      enrollmentState: "enrolled",
      endpoint: "local://desktop",
      identityFingerprint: "local-host",
      supportedTransports: ["local-host-command"],
      roles: ["safe-command-runner", "artifact-store"],
      healthState: "unknown",
      notes: [
        "Default passive local node record. Executable capabilities are enabled only through host-mediated policy.",
      ],
    },
    {
      id: "compute-gx10",
      label: "GX10 Inference Server",
      kind: "ssh-remote",
      trustTier: "user-owned-remote",
      enrollmentState: "enrolled",
      endpoint: "ssh://rlab@gx10-23bd.local",
      identityFingerprint: "gx10-23bd.local",
      supportedTransports: ["ssh"],
      roles: ["safe-command-runner", "service-host", "artifact-store", "model-host"],
      healthState: "ready",
      lastVerifiedAt: "2026-05-10",
      probe: {
        os: "Ubuntu 24.04.4 LTS",
        arch: "aarch64",
        cpuCores: 20,
        ramGb: 121,
        gpu: ["NVIDIA GB10 CC 12.1"],
        modelEndpoints: ["http://192.168.1.77:30004/v1"],
        checkedAt: "2026-05-16",
      },
      notes: [
        "SSH and active llama.cpp model endpoint verified on 2026-05-16.",
        "Credentials are intentionally not stored in repository defaults; use local SSH agent, keychain, or host vault.",
        "Use NGC containers for GPU workloads on GB10 CC 12.1.",
      ],
    },
    {
      id: "compute-nas-backup",
      label: "NAS Backup Storage",
      kind: "ssh-remote",
      trustTier: "user-owned-remote",
      enrollmentState: "enrolled",
      endpoint: "ssh://nas",
      identityFingerprint: "nas",
      supportedTransports: ["ssh"],
      roles: ["artifact-store"],
      healthState: "ready",
      lastVerifiedAt: "2026-05-10",
      probe: {
        os: "Synology DSM-compatible Linux",
        arch: "x86_64",
        toolchains: ["ssh"],
        checkedAt: "2026-05-10",
      },
      notes: [
        "NAS SSH alias verified on 2026-05-10.",
        "Backup root is currently /volume1/Reosnant Backup/; the directory name is misspelled on disk.",
        "Credentials are intentionally not stored in repository defaults; use SSH config, SSH agent, keychain, or host vault.",
      ],
    },
  ],
  jobs: [],
  artifacts: [],
  audit: [],
};

export const modelStrategy: ModelStrategyState = {
  profileId: "personal-studio-default",
  label: "Personal Studio Strategy",
  summary:
    "Route each workload to the cheapest acceptable model first, then escalate through agreed fallbacks rather than always selecting the strongest model.",
  fallbackChains: [
    {
      id: "chain-core-fast",
      label: "Core Fast Chain",
      rule: "Try the main fast route first, then Z.AI GLM, premium cloud, then remote or local fallback.",
      orderedRoutes: [
        { providerProfileId: "shared-minimax", runtimeNodeId: "node-minimax-cloud", model: "MiniMax-M3", costPosture: "subscription", note: "Default fast route for Augmentor and the Engineer Agent." },
        { providerProfileId: "shared-zai-glm", runtimeNodeId: "node-zai-glm-cloud", model: "zai/glm-5.2", costPosture: "paid-api", note: "OpenClaw/Z.AI GLM fallback when the primary subscription route is unavailable." },
        { providerProfileId: "shared-openai", runtimeNodeId: "node-openai-cloud", model: "gpt-5.5", costPosture: "subscription", note: "Premium fallback for demanding moments." },
        { providerProfileId: "gx10-local-llama", runtimeNodeId: "node-gx10-qwen", model: "Qwen3.6-35B-A3B-Q4_K_M.gguf", costPosture: "free-local", note: "Verified local-owned GX10 route for private LAN inference." },
      ],
      lastResortRoute: {
        providerProfileId: "shared-local",
        runtimeNodeId: "node-local-resurrect",
        model: "batiai/gemma4-e2b:q4",
        costPosture: "emergency-only",
        note: "Desktop-local hard floor.",
      },
    },
    {
      id: "chain-routine-economical",
      label: "Routine Economical Chain",
      rule: "Prefer the subscription route for routine work, then Z.AI GLM, then the local floor.",
      orderedRoutes: [
        { providerProfileId: "shared-minimax", runtimeNodeId: "node-minimax-cloud", model: "MiniMax-M3", costPosture: "subscription", note: "Routine and cron-style work." },
        { providerProfileId: "shared-zai-glm", runtimeNodeId: "node-zai-glm-cloud", model: "zai/glm-5.2", costPosture: "paid-api", note: "Z.AI GLM fallback for routine work when the subscription route is unavailable." },
      ],
      lastResortRoute: {
        providerProfileId: "shared-local",
        runtimeNodeId: "node-local-resurrect",
        model: "batiai/gemma4-e2b:q4",
        costPosture: "emergency-only",
        note: "Desktop-local economical fallback.",
      },
    },
    {
      id: "chain-archive-premium",
      label: "Archive Premium Chain",
      rule: "Archive interpretation should stay premium-first and hard-stop before dropping below acceptable quality.",
      orderedRoutes: [
        { providerProfileId: "shared-openai", runtimeNodeId: "node-openai-cloud", model: "gpt-5.5", costPosture: "subscription", note: "Preferred ingest quality route." },
        { providerProfileId: "shared-zai-glm", runtimeNodeId: "node-zai-glm-cloud", model: "zai/glm-5.2", costPosture: "paid-api", note: "Z.AI GLM premium fallback when the preferred ingest route is unavailable." },
        { providerProfileId: "shared-minimax", runtimeNodeId: "node-minimax-cloud", model: "MiniMax-M3", costPosture: "subscription", note: "Temporary fallback if premium route is unavailable." },
        { providerProfileId: "gx10-local-llama", runtimeNodeId: "node-gx10-qwen", model: "Qwen3.6-35B-A3B-Q4_K_M.gguf", costPosture: "free-local", note: "Local inference last resort before hard-stop." },
      ],
    },
  ],
  workloadStrategies: [
    {
      id: "strategy-augmentor-primary",
      label: "Augmentor Primary Chat",
      workloadClass: "primary-chat",
      ownerType: "agent",
      ownerId: "strategist.core",
      primaryRoute: { providerProfileId: "shared-minimax", runtimeNodeId: "node-minimax-cloud", model: "MiniMax-M3", costPosture: "subscription" },
      fallbackChainId: "chain-core-fast",
      hardStopWhenNoFallback: false,
      notes: ["Primary trusted conversation should stay on the fast subscription route when possible."],
    },
    {
      id: "strategy-engineer-recovery",
      label: "Resonant Engineer Recovery",
      workloadClass: "recovery",
      ownerType: "agent",
      ownerId: "setup.core",
      primaryRoute: { providerProfileId: "shared-local", runtimeNodeId: "node-local-resurrect", model: "batiai/gemma4-e2b:q4", costPosture: "emergency-only" },
      fallbackChainId: "chain-core-fast",
      hardStopWhenNoFallback: false,
      notes: ["Recovery starts at the local floor, then promotes to the best validated stronger route."],
    },
    {
      id: "strategy-archive-ingest",
      label: "Archive Ingest",
      workloadClass: "archive-ingest",
      ownerType: "workload",
      ownerId: "archive-ingest",
      primaryRoute: { providerProfileId: "shared-openai", runtimeNodeId: "node-openai-cloud", model: "gpt-5.5", costPosture: "subscription" },
      fallbackChainId: "chain-archive-premium",
      hardStopWhenNoFallback: true,
      notes: ["Archive interpretation should not silently degrade below premium quality without explicit approval."],
    },
    {
      id: "strategy-routine-background",
      label: "Routine Background Work",
      workloadClass: "routine",
      ownerType: "workload",
      ownerId: "routine",
      primaryRoute: { providerProfileId: "shared-minimax", runtimeNodeId: "node-minimax-cloud", model: "MiniMax-M3", costPosture: "subscription" },
      fallbackChainId: "chain-routine-economical",
      hardStopWhenNoFallback: false,
      notes: ["Cron, heartbeat, and routine delegated work should prefer economical routes."],
    },
  ],
  emergencyPolicy: {
    preferBestAvailable: true,
    orderedPromotionTargets: [
      { providerProfileId: "shared-minimax", runtimeNodeId: "node-minimax-cloud", model: "MiniMax-M3", costPosture: "subscription", note: "Promote to the MiniMax M3 cloud route first." },
      { providerProfileId: "shared-zai-glm", runtimeNodeId: "node-zai-glm-cloud", model: "zai/glm-5.2", costPosture: "paid-api", note: "Promote to Z.AI GLM when MiniMax is unavailable." },
      { providerProfileId: "shared-openai", runtimeNodeId: "node-openai-cloud", model: "gpt-5.5", costPosture: "subscription", note: "Premium fallback when the fast route is unavailable." },
    ],
    hardFloorRoute: {
      providerProfileId: "shared-local",
      runtimeNodeId: "node-local-resurrect",
      model: "batiai/gemma4-e2b:q4",
      costPosture: "emergency-only",
      note: "Last resort local floor that should always remain available.",
    },
    note: "Emergency mode should auto-detect the best available model, but always preserve a guaranteed local floor.",
  },
};

export const agents: AgentDefinition[] = [
  {
    id: "strategist.core",
    displayName: "Augmentor",
    trustTier: "core",
    workspaceBehavior: "primary",
    providerProfileId: "shared-minimax",
    fallbackProviderProfileId: "shared-openai",
    archiveReadScopes: ["constitution", "protocols", "living-archive", "session-memory"],
    archiveIntakeWriteScopes: [],
    canWriteKnowledgePages: false,
    channelIds: ["desktop-main", "telegram-primary", "telegram-field"],
  },
  {
    id: "setup.core",
    displayName: "Resonant Engineer Agent",
    trustTier: "core",
    workspaceBehavior: "delegated",
    providerProfileId: "shared-local",
    fallbackProviderProfileId: "shared-minimax",
    archiveReadScopes: ["configuration", "constitution", "protocols", "living-archive", "review"],
    archiveIntakeWriteScopes: [],
    canWriteKnowledgePages: false,
    channelIds: ["desktop-setup", "desktop-engineer"],
  },
  {
    id: "archive-ingest.core",
    displayName: "Resonant Ingest Agent",
    trustTier: "core",
    workspaceBehavior: "background",
    providerProfileId: "shared-minimax",
    fallbackProviderProfileId: "shared-openai",
    archiveReadScopes: ["intake", "constitution", "protocols", "living-archive"],
    archiveIntakeWriteScopes: ["ingest/intake", "ingest/review"],
    canWriteKnowledgePages: true,
    channelIds: [],
  },
  {
    id: "hermes.agent",
    displayName: "Hermes",
    trustTier: "addon",
    workspaceBehavior: "delegated",
    providerProfileId: "shared-minimax",
    fallbackProviderProfileId: "shared-local",
    archiveReadScopes: ["living-archive/context"],
    archiveIntakeWriteScopes: ["LivingArchive/INTAKE/hermes"],
    canWriteKnowledgePages: false,
    channelIds: ["desktop-hermes"],
  },
];

export const channels: ChannelDefinition[] = [
  {
    id: "desktop-main",
    type: "desktop",
    label: "Desktop Main",
    owningAgentId: "strategist.core",
    strategistIdentityId: "strategist.identity",
    enabled: true,
    sessionMode: "shared-identity",
    workspaceId: "workspace-main",
    metadata: { surface: "primary-shell" },
  },
  {
    id: "desktop-setup",
    type: "desktop",
    label: "Engineering Console",
    owningAgentId: "setup.core",
    strategistIdentityId: "strategist.identity",
    enabled: true,
    sessionMode: "isolated-session",
    workspaceId: "workspace-setup",
    metadata: { surface: "system-configuration" },
  },
  {
    id: "desktop-engineer",
    type: "desktop",
    label: "Recovery Console",
    owningAgentId: "setup.core",
    strategistIdentityId: "strategist.identity",
    enabled: true,
    sessionMode: "isolated-session",
    workspaceId: "workspace-recovery",
    metadata: { surface: "emergency-recovery" },
  },
  {
    id: "telegram-primary",
    type: "telegram",
    label: "Telegram Primary",
    owningAgentId: "strategist.core",
    strategistIdentityId: "strategist.identity",
    enabled: false,
    sessionMode: "shared-identity",
    workspaceId: "workspace-main",
    metadata: { botName: "augmentor_primary", route: "trusted-main" },
  },
  {
    id: "telegram-field",
    type: "telegram",
    label: "Telegram Field",
    owningAgentId: "strategist.core",
    strategistIdentityId: "strategist.identity",
    enabled: false,
    sessionMode: "isolated-session",
    workspaceId: "workspace-field",
    metadata: { botName: "augmentor_field", route: "field-capture" },
  },
  {
    id: "desktop-hermes",
    type: "desktop",
    label: "Hermes",
    owningAgentId: "hermes.agent",
    strategistIdentityId: "strategist.identity",
    enabled: false,
    sessionMode: "isolated-session",
    workspaceId: "workspace-hermes",
    metadata: { surface: "hermes-addon", addonId: "addon.hermes" },
  },
];

export const workspaces: WorkspaceDefinition[] = [
  {
    id: "workspace-main",
    kind: "main",
    owningEntityId: "strategist.core",
    title: "Trusted Main Workspace",
    visibility: "user-facing",
    sharedArtifacts: true,
    surfaces: ["chat", "decision-log", "memory-peek"],
    channelIds: ["desktop-main", "telegram-primary"],
  },
  {
    id: "workspace-setup",
    kind: "delegated",
    owningEntityId: "setup.core",
    title: "Engineering & Configuration",
    visibility: "user-facing",
    sharedArtifacts: false,
    surfaces: ["setup-checklist", "provider-vault", "addon-installer"],
    channelIds: ["desktop-setup"],
  },
  {
    id: "workspace-recovery",
    kind: "delegated",
    owningEntityId: "setup.core",
    title: "Emergency Recovery",
    visibility: "user-facing",
    sharedArtifacts: false,
    surfaces: ["diagnosis-log", "recovery-checklist", "change-report"],
    channelIds: ["desktop-engineer"],
  },
  {
    id: "workspace-field",
    kind: "delegated",
    owningEntityId: "strategist.core",
    title: "Field Capture",
    visibility: "user-facing",
    sharedArtifacts: true,
    surfaces: ["telegram-capture", "archive-intake"],
    channelIds: ["telegram-field"],
  },
  {
    id: "workspace-hermes",
    kind: "delegated",
    owningEntityId: "hermes.agent",
    title: "Hermes Integration",
    visibility: "user-facing",
    sharedArtifacts: false,
    surfaces: ["chat", "dashboard", "kanban", "profiles", "slashgoal", "archivist", "compatibility-audit"],
    channelIds: ["desktop-hermes"],
  },
];

const strategistSeedMessage = (threadId: string, channelId: string) => ({
  id: `${threadId}:seed-1`,
  threadId,
  channelId,
  role: "assistant" as const,
  author: "Augmentor",
  createdAt: "2026-04-22T09:00:00.000Z",
  content:
    "I am Augmentor, the main Strategist for ResonantOS. This shell is now structured so you can talk to me directly, while add-ons and delegated agents stay scoped behind the system.",
});

const engineerSeedMessage = (threadId: string, channelId: string) => ({
  id: `${threadId}:seed-1`,
  threadId,
  channelId,
  role: "assistant" as const,
  author: "Resonant Engineer Agent",
  createdAt: "2026-04-23T08:00:00.000Z",
  content:
    "Recovery console online. I am the Resonant Engineer Agent. I handle diagnosis, recovery research when network access exists, documentation checks, change tracking, and the final repair report for the larger Strategist model.",
});

export const conversationThreads: ConversationThread[] = [
  {
    id: "thread-main-desktop",
    title: "Desktop Main Thread",
    owningAgentId: "strategist.core",
    workspaceId: "workspace-main",
    channelId: "desktop-main",
    summary: "Primary trusted conversation with the Strategist inside the ResonantOS shell.",
    messages: [strategistSeedMessage("thread-main-desktop", "desktop-main")],
  },
  {
    id: "thread-field-capture",
    title: "Field Capture Thread",
    owningAgentId: "strategist.core",
    workspaceId: "workspace-field",
    channelId: "telegram-field",
    summary: "Separate field-capture context for Telegram or mobile-style intake flows.",
    messages: [strategistSeedMessage("thread-field-capture", "telegram-field")],
  },
  {
    id: "thread-recovery-engineer",
    title: "Emergency Recovery",
    owningAgentId: "setup.core",
    workspaceId: "workspace-recovery",
    channelId: "desktop-engineer",
    summary: "Resonant Engineer Agent emergency workspace for diagnosis, repair logging, and postmortem reporting.",
    messages: [engineerSeedMessage("thread-recovery-engineer", "desktop-engineer")],
  },
];

export const chatProjects: ChatProject[] = [];

export const recoverySession = {
  active: false,
  engineerAgentId: "setup.core",
  engineerThreadId: "thread-recovery-engineer",
  lastNormalThreadId: "thread-main-desktop",
  checklist: [
    {
      id: "facts",
      label: "Establish facts",
      description: "Confirm the local recovery floor, inspect runtime state, and write the first diagnosis down.",
      status: "pending" as const,
    },
    {
      id: "better-brain",
      label: "Restore better brain",
      description: "Probe internet, provider routes, and remote/local nodes to find a stronger model than the local recovery floor.",
      status: "pending" as const,
    },
    {
      id: "promote",
      label: "Promote runtime",
      description: "Validate the best stronger route and promote the Engineer Agent onto it while preserving local fallback.",
      status: "pending" as const,
    },
    {
      id: "deep-diagnosis",
      label: "Deep diagnosis",
      description: "With a stronger model active, inspect the primary fault, docs, logs, and code paths in detail.",
      status: "pending" as const,
    },
    {
      id: "changes",
      label: "Track changes",
      description: "Record each system change so the recovery path can be audited or rolled forward safely.",
      status: "pending" as const,
    },
    {
      id: "report",
      label: "Write report",
      description: "Produce a recovery report for the larger Strategist model after the system is stable again.",
      status: "pending" as const,
    },
  ],
  changeLog: [],
};

export const archivePolicy: ArchivePolicy = {
  strategistIdentityId: "strategist.identity",
  ingestServiceId: "archive-ingest.core",
  intakeRoots: [
    "_LivingArchive/INTAKE/transcripts",
    "_LivingArchive/INTAKE/external-agents",
  ],
  knowledgeRoots: [
    "_LivingArchive/WIKI/summaries",
    "_LivingArchive/WIKI/entities",
    "_LivingArchive/WIKI/concepts",
    "_LivingArchive/WIKI/syntheses",
  ],
  reviewQueueRoot: "_LivingArchive/REVIEW",
  approvalPolicy: {
    defaultTier: "strategist-review",
    autoApproveIntents: ["summary-refresh", "metadata-refresh"],
    humanReviewSourceTypes: ["constitution", "protocol", "philosophy", "manifesto"],
    humanReviewPageTypes: ["synthesis", "future-asset", "constitution-note", "protocol-note"],
    notes: [
      "Strategist review is the default for archive promotion.",
      "Human review is reserved for doctrine-sensitive or high-impact cases.",
      "Auto-approve is limited to narrow, proven-safe refresh classes.",
    ],
  },
  actorPolicies: [
    {
      actorId: "strategist.core",
      actorType: "core-agent",
      readScopes: ["constitution", "protocols", "living-archive", "intake"],
      intakeWriteScopes: [],
      canWriteKnowledgePages: false,
      canRequestIngest: true,
    },
    {
      actorId: "archive-ingest.core",
      actorType: "service",
      readScopes: ["constitution", "protocols", "living-archive", "intake", "review"],
      intakeWriteScopes: ["_LivingArchive/REVIEW"],
      canWriteKnowledgePages: true,
      canRequestIngest: true,
    },
    {
      actorId: "addon.openclaw",
      actorType: "addon",
      readScopes: ["living-archive/context"],
      intakeWriteScopes: ["_LivingArchive/INTAKE/external-agents"],
      canWriteKnowledgePages: false,
      canRequestIngest: true,
    },
  ],
  notes: [
    "Add-ons can read scoped archive views and deposit raw artifacts into intake roots.",
    "Only the Strategist-owned Resonant Ingest Agent can create or update trusted knowledge pages.",
  ],
};

export const archiveAutomationPolicy: ArchiveAutomationPolicy = {
  autoSyncEnabled: false,
  aiMemoryBuilds: "off",
};

// P1-e: do not trust by omission. A bundled manifest with NO provenance is
// marked dev/internal/unreviewed (sideloaded-unverified / unverified) rather than
// silently defaulting to curated-signed / verified.
const defaultProvenanceTier = (manifest: AddOnManifest, source: AddOnInstallation["source"]): AddOnInstallation["provenanceTier"] =>
  source === "sideload" || !manifest.provenance ? "sideloaded-unverified" : (manifest.provenance.tier ?? "curated-signed");

const defaultVerificationState = (
  manifest: AddOnManifest,
  source: AddOnInstallation["source"],
): AddOnInstallation["verificationState"] =>
  source === "sideload" || !manifest.provenance ? "unverified" : (manifest.provenance.verificationState ?? "verified");

export const createDefaultInstallation = (manifest: AddOnManifest, source: AddOnInstallation["source"]): AddOnInstallation => ({
  addonId: manifest.id,
  source,
  provenanceTier: defaultProvenanceTier(manifest, source),
  verificationState: defaultVerificationState(manifest, source),
  installed: false,
  enabled: false,
  status: "available",
  grantedCapabilities: manifest.requestedCapabilities.map((item) => ({ ...item, granted: false })),
  recommendedGrantPresetIds: (manifest.grantPresets ?? []).map((preset) => preset.id),
  grantRecommendationSource: manifest.grantPresets?.length ? "preset-bundle" : "manifest-request",
  privateProviderProfileIds: [],
  config: {},
  notes: ["Not installed yet."],
});

export const buildDefaultState = (manifests: AddOnManifest[]): ResonantShellState => {
  const installations = Object.fromEntries(
    manifests.map((manifest) => [manifest.id, createDefaultInstallation(manifest, "bundled")]),
  );

  return {
    strategistIdentity: {
      id: "strategist.identity",
      defaultName: "Augmentor",
      trustNote: "Primary trusted AI identity. Add-on agents are delegated, not equivalent.",
    },
    coreServices,
    providers: providerProfiles,
    runtimeNodes,
    providerRouting,
    computeFabric,
    modelStrategy,
    agents,
    channels,
    workspaces,
    archivePolicy,
    archiveAutomationPolicy,
    chatProjects,
    conversationThreads,
    transcriptLedger: [],
    contextMemoryStates: [],
    goalWorkspaces: [],
    recoverySession,
    installations,
    uiPreferences: {
      activeSection: "overview",
      activeChatThreadId: "thread-main-desktop",
      activeCostPosture: "subscription" as const,
      pinnedChatThreadIds: ["thread-main-desktop"],
      pinnedChatProjectIds: [],
      leftSidebarOpen: true,
      chatSidebarOpen: true,
      workspaceLayout: "main-chat",
      chatHistoryOpen: false,
      chatSidebarWidth: 520,
      recommendedAddOnsReviewed: false,
      windowZoom: 1,
      pendingOpenCodeWorkspaceId: null,
      browserWorkspace: {
        activeTabId: "tab-1",
        tabs: [
          {
            id: "tab-1",
            label: "resonantos.com",
            url: "https://resonantos.com",
            history: ["https://resonantos.com"],
            historyIndex: 0,
          },
        ],
        controlledSession: {
          sessionId: null,
          status: "idle",
          url: null,
          title: null,
          error: null,
          lastSyncedAt: null,
        },
      },
      theme: "resonant-dark",
    },
    distributionModel: "curated-plus-sideload",
  };
};
